# Changes here will be overwritten by Copier
_commit: v7.2.0-4-g738b107
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-ulid
project_description: Create Universally Unique Lexicographically Sortable Identifiers
    (ULID) in transformations.
project_slug: ulid
project_type: plugin
pypi: true

